# nginx.conf — balanceador TCP (stream) para servidor.py
# Distribuye conexiones entrantes en :5100 entre servidor_1 y servidor_2

events {
    worker_processes  auto;
}

stream {
    upstream pfo3_workers {
        least_conn;
        server servidor_1:5100;
        server servidor_2:5100;
    }

    server {
        listen      5100;
        proxy_pass  pfo3_workers;

        proxy_connect_timeout   5s;
        proxy_timeout           60s;
    }
}
